url: https://rufusraghunath.com
enforce_ssl: rufusraghunath.com
title: Rufus Raghunath
tagline: 'Where “build the right thing” meets “build the thing right”'
description: 'Where “build the right thing” meets “build the thing right”'
base_url: ""
github_username: rufusraghunath
twitter_username: rufusraghunath
linkedin_username: rufusraghunath
paginate: 3
markdown: kramdown
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  sass_dir: _sass
  style: :compressed
google_analytics: UA-98721582-1
