url: https://rufusraghunath.com
enforce_ssl: rufusraghunath.com
title: Rufus Raghunath
tagline: Meditations on the idiosyncracies of software development
description: >
  Functional programmer. Agile consultant. I like to think about things.
email: rraghun@thoughtworks.com
base_url: ""
github_username: rufusraghunath
linkedin_username: rufusraghunath
paginate: 5
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  sass_dir: _sass
  style: :compressed
google_analytics: UA-98721582-1
