url: https://rufusraghunath.com
enforce_ssl: rufusraghunath.com
title: Rufus Raghunath
tagline: Consultant. Armchair philosopher. Accidental frontend evangelist.
description: Consultant. Armchair philosopher. Accidental frontend evangelist.
email: rraghun@thoughtworks.com
base_url: ""
github_username: rufusraghunath
twitter_username: rufusraghunath
linkedin_username: rufusraghunath
paginate: 3
markdown: kramdown
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  sass_dir: _sass
  style: :compressed
google_analytics: UA-98721582-1
